config/routes.rb
Inz::Application.routes.draw do

  resources :auctions, :only => [:index, :show] do
    resources :ratings, :only => [:index, :create]
    get :result, :on => :collection
    get :search, :on => :collection
  end
  
  resources :users do
  	member do
  		get :watching, :watchers
  	end
  	resources :userprojects, :only => [:index]
  	resources :blogposts do
  		member do
  			get :admin
  		end
  	end
  	resources :portfolios
  	resources :bonuspoints, :only => [:index] do
  		member do
  			get :addfromblog
  		end
  	end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :blogposts
  resources :blogcomments do
  	member do
  		get :admin
  	end
  end
  resources :bonuspoints
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match 'signout',  :to => 'sessions#destroy'
  match '/ver', :to => 'users#mail_ver'
  match '/find', :to => 'users#find'
  match '/delete', :to => 'users#delete'

  namespace :panel do
    
    resources :auctions, :except => [:show] do
      resources :communications, :only => [:new, :create]
      get :offers, :on => :member # offers#index dla wlasnych ofert zarezerwowane
      get :user_form, :on => :collection
      resources :offers, :only => [:destroy, :new, :create] do
      end
    end
    
    resources :offers, :only => [:index] do
      post :to_reject, :on => :member
    end
    resources :comments do
      get :queue, :on => :collection
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    
    resources :projects, :only => :index
  end

  namespace :admin do
    resources :alerts, :only => [:index, :show, :destroy]
    resources :auctions, :except => [:show] do
      resources :offers, :only => [:destroy] do
        get :recovery, :on => :member
      end
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    resources :groups, :except => [:show]
    resources :tags, :except => [:show]
    resources :communications, :only => [:destroy]
    resources :users do
    	get :blogposts, :on => :member
      resources :comments, :only => [:index, :edit, :update]
    end
  end
  match 'admin/users/:id/points', :to => 'admin/users#points'
  match 'admin/users/:id/editpoints', :to => 'admin/users#editpoints'
  match 'admin/users/:id/status/:status/delete', :to => 'admin/users#delete'
  match 'admin/blogposts', :to => 'admin/users#blogposts'
  match 'admin/blogposts/:id', :to => 'admin/users#blogpostok'
  match 'admin/blogpost/:id', :to => 'admin/users#blogpostedit'
  match 'admin/blogpost/:id/edit', :to => 'admin/users#blogpostedit2'
  match 'admin/blogposts/delete/:blogpost', :to => 'admin/users#deleteblogpost'
  match 'admin/blogcomments', :to => 'admin/users#blogcomments'
  match 'admin/blogcomments/:id', :to => 'admin/users#blogcommentok'
  match 'admin/blogcomments/delete/:blogcomment', :to => 'admin/users#deleteblogcomment'
  
  scope :module => "project" do
    resources :projects do
      resource :info, :only => [:show, :update], :controller => "info"
      resources :members, :only => [:index, :update, :destroy]
      resources :files, :except => [:edit]
      resources :invitations, :except => [:show, :update] do
        get :accept, :on => :member
        get :reject, :on => :member
        get :cancel, :on => :member
      end
      resources :topics do
      	resources :posts, :except => [:index, :show]
      end
      resources :tickets do
        get :take, :on => :member
        get :give, :on => :member
        get :end, :on => :member
      end
    end
  end
  	
  resources :alerts, :only => [:create]
  
  
  
  root :to =>  "auctions#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  STATUSES = {:active => 0, :pending => 1, :deleted => 2}
  LEVELS = {:auction => 0, :project => 1}

  attr_accessor :allowed_points
  
  belongs_to :author, :class_name => "User"
  belongs_to :receiver, :class_name => "User"
  belongs_to :auction
  belongs_to :project
  has_many :values, :class_name => "CommentValue", :dependent => :destroy, :include => [:keyword]

  validates :values, :associated => true

  scope :pending, ->{ where(:status => STATUSES[:pending])}
  scope :active, ->{ where(:status => STATUSES[:active])}
  default_scope includes(:values)

  before_save :default_attributes
  before_validation :check_points

  def self.create_from_auction(auction)
    owner = auction.owner
    offerer = auction.won_offer.offerer
    2.times do
      self.create(
        :auction => auction,
        :author => owner,
        :receiver => offerer,
        :level => LEVELS[:auction]
      )
      owner, offerer = offerer, owner
    end
  end

  def self.create_from_project_for_owner(project)
    self.create(
      :project => project,
      :author_id => project.leader_id,
      :receiver_id => project.owner_id,
      :level => LEVELS[:project]
    )
    self.create(
      :project => project,
      :author_id => project.owner_id,
      :receiver_id => project.leader_id,
      :level => LEVELS[:project]
    )
  end

  def self.create_from_owner_comment(comment)
    project = comment.project

    users = project.user_ids - [project.leader_id, project.owner_id]
    users.each do |user_id|
      author_id = project.leader_id
      receiver_id = user_id
      2.times do
        self.create(
          :project => project,
          :author_id => author_id,
          :receiver_id => receiver_id,
          :level => LEVELS[:project]
        )
        author_id, receiver_id = receiver_id, author_id
      end
    end
  end

  def points_mode?
    self.level?(:project) && ![self.author_id, self.receiver_id].include?(self.project.owner_id)
  end

  def owner_comment?
    !self.project.nil? && self.project.owner_id == self.author_id
  end

  def activate!
    self.status = STATUSES[:active]
    self.save
  end

  def delete!
    self.status = STATUSES[:deleted]
    self.save
  end

  def status? status
    self.status == STATUSES[status]
  end

  def level? level
    self.level == LEVELS[level]
  end

  private
  def default_attributes
    self.status = STATUSES[:pending] if self.status.nil?
  end

  def check_points
    #unless self.allowed_points.nil? && (self.allowed_points >= self.values.sum(:rating))
    # self.values.each do |v| v.errors.add(:rating, "Przekroczono dozwolona ilosc punktow") end
    #end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  before_filter :load_comment, :only => [:edit, :update, :destroy]
  before_filter :form_data, :only => [:edit, :update]
  
  def index
    @comments = Comment.
      where("author_id=:id OR receiver_id=:id", {:id => params[:user_id]}).
      paginate :page => params[:page], :per_page => 15
  end

  def edit
    session[:referer] = request.referer
    title_t
  end

  def update
    @values.each
    if @comment.update_attributes(params[:comment])
      redirect_to session[:referer], :notice => flash_t
    else
      title_t :edit
      render :edit
    end
  end

  private
  def form_data
    @author = @comment.author
    @receiver = @comment.receiver
    @auction = @comment.auction
    @project = @comment.project
    @values = @comment.values
    @keywords = CommentKeyword.all
    
    if @values.empty?
      @values = (params[:comment_value].nil?)?
        CommentKeyword.create_comment_values : @comment.values.build(params[:comment_value].values)
    end
  end

  def load_comment
    @comment = Comment.where(:id => params[:id]).first
  end
end

app/controllers/panel/comments_controller.rb
class Panel::CommentsController < Panel::ApplicationController
  before_filter :comment_and_form_data, :only => [:edit, :update]
    
  def index	
    @status = params[:status] || :received
    title_t @status
    @comments = current_user.send(@status.to_s+"_comments").active.paginate :per_page => 15, :page => params[:page]
  end
  
  def queue
    title_t
    @comments = current_user.written_comments.pending.all.paginate :per_page => 15, :page => params[:page]
    render :index
  end

  def edit
    title_t
  end

  def update
    if @comment.save
      @comment.activate!
      if @comment.owner_comment?
        Comment.create_from_owner_comment(@comment)
      end
      Sender.user_commented(@comment).deliver
      redirect_to queue_panel_comments_path, :notice => flash_t
    else
      title_t :edit
      render :edit
    end
  end

  def show
    title_t
    @comment = Comment.active.find(params[:id])
  end

  private
  def comment_and_form_data
    @comment = current_user.written_comments.pending.find(params[:id])

    if @comment.points_mode?
      @leader_comment = Comment.
        where(:project_id => @comment.project.id).
        where(:receiver_id => @comment.project.leader_id).
        first
      @allowed_points = @leader_comment.values.sum(:rating);
      @comment.allowed_points = @allowed_points
    end

    @keywords = CommentKeyword.all
    @receiver = @comment.receiver
    @values = (params[:comment_value].nil?)?
      CommentKeyword.create_comment_values : @comment.values.build(params[:comment_value].values)
  end
end

app/views/admin/comments/edit.html.erb
<% content_for :head do -%>
  <%= javascript_include_tag 'jquery.rating.js' %>
  <%= stylesheet_link_tag 'jquery.rating' %>
  <script type="text/javascript">
    function count_stars(){
      var count = 0;
      $(".star").each(function(){
        if($(this).attr("checked")) count += parseInt($(this).val());
      });
      var pointsSpan = $("#points").html(count);
      if(allowed_points > 0 && count > allowed_points) {
        pointsSpan.toggleClass("error", true);
        pointsSpan.toggleClass("notice", false);
      } else {
        pointsSpan.toggleClass("error", false);
        pointsSpan.toggleClass("notice", true);
      }
      
      return count;
    }

    $(document).ready(function(){
      $(".star").rating({required: false, callback: count_stars});
      count_stars();
      $("form.edit_comment").submit(check_stars);
    });
    var allowed_points = <%= (@allowed_points.nil?)? 0 : @allowed_points %>;

    function check_stars(event){
      if (allowed_points > 0 && allowed_points < count_stars()){
        alert("Punkty przeznaczone na ocenę zostały przekroczone.");
        return false;
      }
      else
        return true;
    };
  </script>
<% end -%>
<div class="prepend-1 append-1">
  <% form_for [:admin, @comment.author, @comment] do |f| -%>

    <%= render "layouts/error_messages", :target => @comment %>
  <p>Od: <%= escape_user(@author) %></p>
    <p>Do: <%= escape_user(@receiver) %> za
<% if @comment.level?(:auction) %> aukcję <%= link_auction(@comment.auction) %>
<% else %> projekt <%= link_to @comment.project.name, project_info_path(@comment.project) %><% end %>
:</p>
    <% unless @allowed_points.nil? %>
    <p>Dozwolona ilość punktów do rozdania: <span id="maxPoints" class="bold notice"><%= @allowed_points %></span></p>
  <% end %>
    <p>
<%= f.label :status %>
      <%= select :comment, :status, statuses_for_select(@comment) %></p>
    <p>Rozdano punkty: <span id="points" class="bold notice">0</span></p>
    <% @values.each do |v| %>
      <%= render "layouts/error_messages", :target => v %>
      <%= fields_for "comment_value", v, :index => "#{v.keyword.id}" do |ff| %>
        <%= ff.hidden_field :keyword_id %>
        <div style="margin-bottom:5px"><%= v.keyword.name.force_encoding("utf-8") %>:</div>
        <% for i in 1..5 %>
          <%= ff.radio_button :rating, i, :class => "star inline", :title => i %>
        <% end %>
        <%= ff.text_field :extra %>
        <br />
      <% end %>
    <% end %>

    <br />
    <%= f.submit "Wystaw" %>
  <% end -%>
</div>

app/views/admin/comments/index.html.erb
<% unless @comments.empty? %>
  <table class="list">
    <thead>
      <tr>
        <td>od</td>
        <td>do</td>
        <td>oceny</td>
        <td>za aukcję</td>
        <td>za projekt</td>
        <td>opcje</td>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |c| %>
        <tr>
          <td><%= link_to escape_user(c.author), c.author %></td>
          <td><%= link_to escape_user(c.receiver), c.receiver %></td>
          <td><% c.values.each do |v| %> <%= v.rating %><% end %></td>
          <td><%= link_auction(c.auction) unless c.auction.nil? %></td>
          <td><%= c.project.name unless c.project.nil? %></td>
          <td>
            <%= link_to "edytuj komentarz", edit_admin_user_comment_path(c.author, c) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
<% else %>
  <div class="notice">Nie znaleziono żadnych aukcji.</div>
<% end %>