config/routes.rb
Inz::Application.routes.draw do

  resources :auctions, :only => [:index, :show] do
    resources :ratings, :only => [:index, :create]
    get :result, :on => :collection
    get :search, :on => :collection
  end
  
  resources :users do
  	member do
  		get :watching, :watchers
  	end
  	resources :userprojects, :only => [:index]
  	resources :blogposts do
  		member do
  			get :admin
  		end
  	end
  	resources :portfolios
  	resources :bonuspoints, :only => [:index] do
  		member do
  			get :addfromblog
  		end
  	end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :blogposts
  resources :blogcomments do
  	member do
  		get :admin
  	end
  end
  resources :bonuspoints
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match 'signout',  :to => 'sessions#destroy'
  match '/ver', :to => 'users#mail_ver'
  match '/find', :to => 'users#find'
  match '/delete', :to => 'users#delete'

  namespace :panel do
    
    resources :auctions, :except => [:show] do
      resources :communications, :only => [:new, :create]
      get :offers, :on => :member # offers#index dla wlasnych ofert zarezerwowane
      get :user_form, :on => :collection
      resources :offers, :only => [:destroy, :new, :create] do
      end
    end
    
    resources :offers, :only => [:index] do
      post :to_reject, :on => :member
    end
    resources :comments do
      get :queue, :on => :collection
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    
    resources :projects, :only => :index
  end

  namespace :admin do
    resources :alerts, :only => [:index, :show, :destroy]
    resources :auctions, :except => [:show] do
      resources :offers, :only => [:destroy] do
        get :recovery, :on => :member
      end
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    resources :groups, :except => [:show]
    resources :tags, :except => [:show]
    resources :communications, :only => [:destroy]
    resources :users do
    	get :blogposts, :on => :member
      resources :comments, :only => [:index, :edit, :update]
    end
  end
  match 'admin/users/:id/points', :to => 'admin/users#points'
  match 'admin/users/:id/editpoints', :to => 'admin/users#editpoints'
  match 'admin/users/:id/status/:status/delete', :to => 'admin/users#delete'
  match 'admin/blogposts', :to => 'admin/users#blogposts'
  match 'admin/blogposts/:id', :to => 'admin/users#blogpostok'
  match 'admin/blogpost/:id', :to => 'admin/users#blogpostedit'
  match 'admin/blogpost/:id/edit', :to => 'admin/users#blogpostedit2'
  match 'admin/blogposts/delete/:blogpost', :to => 'admin/users#deleteblogpost'
  match 'admin/blogcomments', :to => 'admin/users#blogcomments'
  match 'admin/blogcomments/:id', :to => 'admin/users#blogcommentok'
  match 'admin/blogcomments/delete/:blogcomment', :to => 'admin/users#deleteblogcomment'
  
  scope :module => "project" do
    resources :projects do
      resource :info, :only => [:show, :update], :controller => "info"
      resources :members, :only => [:index, :update, :destroy]
      resources :files, :except => [:edit]
      resources :invitations, :except => [:show, :update] do
        get :accept, :on => :member
        get :reject, :on => :member
        get :cancel, :on => :member
      end
      resources :topics do
      	resources :posts, :except => [:index, :show]
      end
      resources :tickets do
        get :take, :on => :member
        get :give, :on => :member
        get :end, :on => :member
      end
    end
  end
  	
  resources :alerts, :only => [:create]
  
  
  
  root :to =>  "auctions#index"

end

app/views/layouts/top_menu/_admin.html.erb
<ul id="mega-menu-1" class="mega-menu">
  <li><%= link_to 'Użytkownicy', admin_users_path %></li>
  <li><%= link_to 'Posty', admin_blogposts_path %></li>
  <li><%= link_to 'Komentarze', admin_blogcomments_path %></li>
  <li><%= link_to 'Aukcje', admin_auctions_path %></li>
  <li><%= link_to 'Zgłoszenia aukcji', admin_alerts_path %></li>
  <li><%= link_to 'Grupy z tagimi', admin_groups_path %>
    <ul>
      <li><p>Tagi</p>
        <ul>
          <li><%= link_to 'Nowy tag', new_admin_tag_path %></li>
          <li><%= link_to 'Lista tagów', admin_tags_path %></li>
        </ul>
      </li>
      <li><p>Grupy</p>
        <ul>
          <li><%= link_to 'Nowa grupa', new_admin_group_path %></li>
          <li><%= link_to 'Lista grup', admin_groups_path %></li>
        </ul>
      </li>
    </ul>
  </li>
  <li><%= link_to 'Prywatne wiadomości', admin_messages_path %>
    <ul>
      <li><p>foldery</p>
        <ul>
          <li><%= link_to 'odebrane', admin_messages_path %></li>
          <li><%= link_to 'wysłane', sent_admin_messages_path %></li>
        </ul>
      </li>
      <li><p>opcje</p>
        <ul>
          <li><%= link_to 'nowa wiadomość', new_admin_message_path %></li>
        </ul>
      </li>
    </ul>
  </li>
  </li>
  <li><%= link_to 'Wyloguj się(' + current_user.to_s + ')', signout_path, :method => :delete %></li>

</ul>
<%= javascript_tag do %>
  $("#mega-menu-1").dcMegaMenu({
  rowItems: '3',
  speed: 'fast'
  });
<% end %>

app/views/layouts/top_menu/_default.html.erb
<ul id="mega-menu-1" class="mega-menu">
  <% if !signed_in? %>
    <li><%= link_to 'Szukaj', search_auctions_path %></li>
    <li><%= link_to 'Logowanie', signin_path, :method => :new %></li>
    <li><%= link_to 'Rejestracja', signup_path, :method => :new %></li>
  <% end %>
  <% if signed_in? %>
    <li><%= link_to 'Szukaj', search_auctions_path %></li>
    <li><%= link_to 'Panel', user_path(current_user) %></li>
    <li><%= link_to 'Nowa aukcja', new_panel_auction_path %></li>
    <li><%= link_to 'Aukcje', panel_auctions_path %>
      <ul>
        <li><p>przeglądaj</p>
          <ul>
            <li><%= link_to 'aktualnie trwające', panel_auctions_path %></li>
            <li><%= raw link_to 'anulowane', panel_auctions_path(:status => :canceled) %></li>
            <li><%= raw link_to 'zakończone', panel_auctions_path(:status => :finished) %></li>
          </ul>
        </li>
        <li><p>opcje</p>
          <ul>
            <li><%= link_to 'wyszukaj aukcję', search_auctions_path %></li>
            <li><%= link_to 'nowa aukcja', new_panel_auction_path %></li>
          </ul>
        </li>
      </ul>
    </li>
    <li><%= link_to 'Prywatne wiadomości', panel_messages_path %>
      <ul>
        <li><p>foldery</p>
          <ul>
            <li><%= link_to 'odebrane', panel_messages_path %></li>
            <li><%= link_to 'wysłane', sent_panel_messages_path %></li>
          </ul>
        </li>
        <li><p>opcje</p>
          <ul>
            <li><%= link_to 'nowa wiadomość', new_panel_message_path %></li>
          </ul>
        </li>
      </ul>
    </li>
    <li><%= link_to 'Oferty', panel_offers_path %>
      <ul>
        <li><p>przeglądaj</p>
          <ul>
            <li><%= raw link_to 'biorące udział', panel_offers_path(:status => :active) %></li>
            <li><%= raw link_to 'wygrane', panel_offers_path(:status => :won) %></li>
          </ul>
        </li>
      </ul>
    </li>
    <li><%= link_to 'Komentarze', panel_comments_path %>
      <ul>
        <li><p>przeglądaj</p>
          <ul>
            <li><%= raw link_to 'oczekujące', queue_panel_comments_path %></li>
            <li><%= raw link_to 'wystawione', panel_comments_path(:status => :written) %></li>
            <li><%= raw link_to 'otrzymane', panel_comments_path(:status => :received) %></li>
          </ul>
        </li>
      </ul>
    </li>
    <li><%= link_to 'Projekty', panel_projects_path %>
    </li>
    <li><%= link_to 'Wyloguj się(' + current_user.to_s + ')', signout_path, :method => :delete %></li>
  <% end %>
</ul>
<%= javascript_tag do %>
  $("#mega-menu-1").dcMegaMenu({
  rowItems: '3',
  speed: 'fast'
  });
<% end %>