config/routes.rb
Inz::Application.routes.draw do

  resources :auctions, :only => [:index, :show] do
    resources :ratings, :only => [:index, :create]
    get :result, :on => :collection
    get :search, :on => :collection
  end
  
  resources :users do
  	member do
  		get :watching, :watchers
  	end
  	resources :userprojects, :only => [:index]
  	resources :blogposts do
  		member do
  			get :admin
  		end
  	end
  	resources :portfolios
  	resources :bonuspoints, :only => [:index] do
  		member do
  			get :addfromblog
  		end
  	end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :blogposts
  resources :blogcomments do
  	member do
  		get :admin
  	end
  end
  resources :bonuspoints
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match 'signout',  :to => 'sessions#destroy'
  match '/ver', :to => 'users#mail_ver'
  match '/find', :to => 'users#find'
  match '/delete', :to => 'users#delete'

  namespace :panel do
    
    resources :auctions, :except => [:show] do
      resources :communications, :only => [:new, :create]
      get :offers, :on => :member # offers#index dla wlasnych ofert zarezerwowane
      get :user_form, :on => :collection
      resources :offers, :only => [:destroy, :new, :create] do
      end
    end
    
    resources :offers, :only => [:index] do
      post :to_reject, :on => :member
    end
    resources :comments do
      get :queue, :on => :collection
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    
    resources :projects, :only => :index
  end

  namespace :admin do
    resources :alerts, :only => [:index, :show, :destroy]
    resources :auctions, :except => [:show] do
      resources :offers, :only => [:destroy] do
        get :recovery, :on => :member
      end
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    resources :groups, :except => [:show]
    resources :tags, :except => [:show]
    resources :communications, :only => [:destroy]
    resources :users do
    	get :blogposts, :on => :member
      resources :comments, :only => [:index, :edit, :update]
    end
  end
  match 'admin/users/:id/points', :to => 'admin/users#points'
  match 'admin/users/:id/editpoints', :to => 'admin/users#editpoints'
  match 'admin/users/:id/status/:status/delete', :to => 'admin/users#delete'
  match 'admin/blogposts', :to => 'admin/users#blogposts'
  match 'admin/blogposts/:id', :to => 'admin/users#blogpostok'
  match 'admin/blogpost/:id', :to => 'admin/users#blogpostedit'
  match 'admin/blogpost/:id/edit', :to => 'admin/users#blogpostedit2'
  match 'admin/blogposts/delete/:blogpost', :to => 'admin/users#deleteblogpost'
  match 'admin/blogcomments', :to => 'admin/users#blogcomments'
  match 'admin/blogcomments/:id', :to => 'admin/users#blogcommentok'
  match 'admin/blogcomments/delete/:blogcomment', :to => 'admin/users#deleteblogcomment'
  
  scope :module => "project" do
    resources :projects do
      resource :info, :only => [:show, :update], :controller => "info"
      resources :members, :only => [:index, :update, :destroy]
      resources :files, :except => [:edit]
      resources :invitations, :except => [:show, :update] do
        get :accept, :on => :member
        get :reject, :on => :member
        get :cancel, :on => :member
      end
      resources :topics do
      	resources :posts, :except => [:index, :show]
      end
      resources :tickets do
        get :take, :on => :member
        get :give, :on => :member
        get :end, :on => :member
      end
    end
  end
  	
  resources :alerts, :only => [:create]
  
  
  
  root :to =>  "auctions#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  STATUSES = {:active => 0, :hidden => 1}
  
  has_many :tags, :dependent => :destroy

  validates :name, :presence => true
  
  default_scope order("name ASC").includes(:tags)

  before_save :default_status, :on => :create

  def to_s
    self.name
  end

  def self.admin_array_to_select
    self.select("id, name").all.collect do |group|
      [group.name, group.id]
    end
  end

  def self.array_to_select
    self.select("id, name").where(:status => STATUSES[:active]).collect do |group|
      [group.name, group.id]
    end
  end

  private
  def default_status
    self.status = STATUSES[:active] if self.status.nil?
  end
end

app/views/shared/_captcha.html.erb
<div class="field">
  <%= f.label :recaptcha, "Przepisz koda z obrazka" %><br />
  <%= raw(get_captcha(:options => {:theme => 'white', :tabindex => 10})) %>
</div>

app/views/shared/_clickable_tags.html.erb
<%# tagi sa wysylane za pomoca parametru  tag_ids, ktory po stronie kontrolera jest hashem {'id' => 'id'} %>
<% groups.each do |g| %>
<div class="span-<%= fieldset_width %><%= cycle("", " last")  %>">
  <fieldset data-sizable="true">
    <legend><%= g.name %></legend>
    <% g.tags.each do |tag| %>
      <%  checked = selected_tag_ids.include?(tag.id) %>
      <%= check_box_tag "tag_ids[#{tag.id}]", tag.id, checked, "data-clickable" => true %>
      <%= label_tag "tag_ids[#{tag.id}]", tag.name, :class => "round" %>
    <% end %>
  </fieldset>
</div>
<% end %>
<div class="clear"></div>
<%= javascript_tag do %>
  clickableLabel();
  sizableFieldset();
<% end %>

app/views/shared/_zaufani.html.erb
<% @user ||= current_user %>
<div>
	<a href="<%= watching_user_path(@user) %>"><%= @user.watching.count %> zaufanych</a> || 
    <a href="<%= watchers_user_path(@user) %>"><%= @user.watchers.count %> zaufało mi</a>
</div>