config/routes.rb
Inz::Application.routes.draw do

  resources :auctions, :only => [:index, :show] do
    resources :ratings, :only => [:index, :create]
    get :result, :on => :collection
    get :search, :on => :collection
  end
  
  resources :users do
  	member do
  		get :watching, :watchers
  	end
  	resources :userprojects, :only => [:index]
  	resources :blogposts do
  		member do
  			get :admin
  		end
  	end
  	resources :portfolios
  	resources :bonuspoints, :only => [:index] do
  		member do
  			get :addfromblog
  		end
  	end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :blogposts
  resources :blogcomments do
  	member do
  		get :admin
  	end
  end
  resources :bonuspoints
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match 'signout',  :to => 'sessions#destroy'
  match '/ver', :to => 'users#mail_ver'
  match '/find', :to => 'users#find'
  match '/delete', :to => 'users#delete'

  namespace :panel do
    
    resources :auctions, :except => [:show] do
      resources :communications, :only => [:new, :create]
      get :offers, :on => :member # offers#index dla wlasnych ofert zarezerwowane
      get :user_form, :on => :collection
      resources :offers, :only => [:destroy, :new, :create] do
      end
    end
    
    resources :offers, :only => [:index] do
      post :to_reject, :on => :member
    end
    resources :comments do
      get :queue, :on => :collection
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    
    resources :projects, :only => :index
  end

  namespace :admin do
    resources :alerts, :only => [:index, :show, :destroy]
    resources :auctions, :except => [:show] do
      resources :offers, :only => [:destroy] do
        get :recovery, :on => :member
      end
    end
    resources :messages, :except => [:edit, :update] do
      get :reply, :on => :member
      get :sent, :on => :collection
    end
    resources :groups, :except => [:show]
    resources :tags, :except => [:show]
    resources :communications, :only => [:destroy]
    resources :users do
    	get :blogposts, :on => :member
      resources :comments, :only => [:index, :edit, :update]
    end
  end
  match 'admin/users/:id/points', :to => 'admin/users#points'
  match 'admin/users/:id/editpoints', :to => 'admin/users#editpoints'
  match 'admin/users/:id/status/:status/delete', :to => 'admin/users#delete'
  match 'admin/blogposts', :to => 'admin/users#blogposts'
  match 'admin/blogposts/:id', :to => 'admin/users#blogpostok'
  match 'admin/blogpost/:id', :to => 'admin/users#blogpostedit'
  match 'admin/blogpost/:id/edit', :to => 'admin/users#blogpostedit2'
  match 'admin/blogposts/delete/:blogpost', :to => 'admin/users#deleteblogpost'
  match 'admin/blogcomments', :to => 'admin/users#blogcomments'
  match 'admin/blogcomments/:id', :to => 'admin/users#blogcommentok'
  match 'admin/blogcomments/delete/:blogcomment', :to => 'admin/users#deleteblogcomment'
  
  scope :module => "project" do
    resources :projects do
      resource :info, :only => [:show, :update], :controller => "info"
      resources :members, :only => [:index, :update, :destroy]
      resources :files, :except => [:edit]
      resources :invitations, :except => [:show, :update] do
        get :accept, :on => :member
        get :reject, :on => :member
        get :cancel, :on => :member
      end
      resources :topics do
      	resources :posts, :except => [:index, :show]
      end
      resources :tickets do
        get :take, :on => :member
        get :give, :on => :member
        get :end, :on => :member
      end
    end
  end
  	
  resources :alerts, :only => [:create]
  
  
  
  root :to =>  "auctions#index"

end

app/controllers/panel/projects_controller.rb
class Panel::ProjectsController < Panel::ApplicationController
  
  def index
    title_t :index
    @projects = current_user.projects.paginate :per_page => 15,
    																					 :page => params[:page]
  end
end

app/controllers/project/application_controller.rb
class Project::ApplicationController < ApplicationController
  before_filter :get_project
  before_filter :check_membership, :except =>[:accept, :reject]
  before_filter :project_active, :except => [:show, :index]
  
  #sprawdzenie uprawnien do edytowania wybranego elementu 
  def can_edit?(page)
    role = Hash.new(false)
    role.merge! @project.user_role(current_user.id).attributes
    role[page]
  end
  
  private
  
  #pobranie projektu
  def get_project      
    unless Project.exists? params[:project_id]
      flash_t_general :error, 'project.dont_exists'
      redirect_to panel_projects_path
      return
    end
        
    @project = Project.find(params[:project_id])
  end
  
  #autoryzacja uzytkownika jako czlonka projektu
  def check_membership
    unless @project.member?(current_user.id)
      flash_t_general :error, 'project.not_participating'
      redirect_to panel_projects_path
      return
    end    
  end
  
  def project_active
    unless @project.active?
      flash_t_general :notice, 'project.not_active'
	  	redirect_to project_info_path(@project)
    end
  end
end

app/controllers/project/files_controller.rb
class Project::FilesController < Project::ApplicationController
  before_filter :check_read_privileges, :except => [:index, :new, :create]
	before_filter :check_edit_privileges, :except => [:index, :show]
	
	def index
		title_t :index
		@files = @project.project_files.paginate :per_page => 15,
		                                         :page => params[:page]
	end
	
	def show	  
		@file = ProjectFile.find(params[:id])
		title_t :show
	end
	
	def new
		@file = ProjectFile.new()
		title_t :new	
	end
	
	def create
		@file = ProjectFile.new(params[:project_file])
		@file.project_id = @project.id
		
		if @file.save
			flash_t :success
			redirect_to project_files_path
		else
			title_t :new
			render :action => :new
		end
	end
	
	def update  
		@file = ProjectFile.find(params[:id])
		@file.description = params[:project_file][:description]
		
		if @file.save
			flash_t :success
			redirect_to project_file_path(@project, @file)
		else
			title_t :show
			render :show
		end
	end
	
	def destroy 
		file = ProjectFile.find(params[:id])
		if file.destroy
			flash_t :success
		end
		redirect_to project_files_path
	end
	
	private
	
	def check_edit_privileges
		unless can_edit? 'file'
			flash_t_general :error, 'error.privileges'
			redirect_to project_files_path
		end
	end
	
	def check_read_privileges
	  unless ProjectFile.exists? params[:id]
	    flash_t_general :error, 'project_file.dont_exists'
	    redirect_to project_files_path
	    return
	  end
	  
	  unless @project.project_file_ids.include?(params[:id].to_i)
	    flash_t_general :error, 'project_file.not_included'
	    redirect_to project_files_path
	  end
	end
end

app/controllers/project/info_controller.rb
class Project::InfoController < Project::ApplicationController
	before_filter :check_privileges, :only => :update
	
  def show
    title_t :show
  end
  
  #zakonczenie projektu lub edycja opisu
  def update
  	if params[:project].nil? && 
  	   @project.owner_id == current_user.id && 
  	   @project.active?
	  	@project.status = Project::STATUSES[:finished]
	  	if @project.save
        @comment = Comment.create_from_project_for_owner(@project)
	      redirect_to edit_panel_comment_path(@comment)
        flash_t :notice, :finishing_update
	    else
	      title_t :show
	      render :show
	    end
  	else
	    @project.description = params[:project][:description]
	    if @project.save
	      flash_t :success
	      redirect_to project_info_path
	    else
	      title_t :show
	      render :show
	    end
    end
  end
  
  private
  
  def check_privileges
  	unless can_edit?('info')
  	  flash_t_general :error, 'error.privileges'
  		redirect_to project_info_path
  	end
  end
end

app/controllers/project/invitations_controller.rb
class Project::InvitationsController < Project::ApplicationController
  before_filter :get_invitation, :only => [:cancel, :destroy]
  before_filter :check_privileges, :except => [:index, :accept, :reject]
  before_filter :get_reciver_invitation, :only => [:accept, :reject]
  
  def index
    title_t :index
    @invitations = @project.invitations.paginate :per_page => 15,
		                                             :page => params[:page]
  end
  
  def new
    title_t :new
    @invitation = Invitation.new(:project_id => @project.id)
  end
  
  def create
    @invitation = Invitation.new(params[:invitation])
    @invitation.project_id = @project.id
    user = User.find_by_login("#{params[:invitation][:user_id]}")
    @invitation.user_id = user.nil? ? 0 : user.id
    
  	#weryfikacja uzytkownika
  	unless User.exists? @invitation.user_id
  	  flash.now[:error] = t('flash.general.user.dont_exists')
  	  render_new
  	  return
  	end
  	
  	if @project.user_ids.include? @invitation.user_id
  		flash.now[:notice] = t('flash.project.members.member_exists')
  		render_new
  	  return 
  	end
  	
  	#weryfikacja roli
  	unless Role.exists? @invitation.role_id
  	  flash.now[:error] = t('flash.general.role.dont_exists')
  	  render_new
  	  return
  	end
  	
  	if @invitation.role_id == Role.get_id('owner') ||
    	 @invitation.role_id == Role.get_id('leader')
    	flash.now[:notice] = t('flash.general.role.invalid_role')
    	render_new
  	  return
    end
    
    inv_users = []
    @project.invitations.each do |i|
      inv_users << i.user_id if i.status == Invitation::STATUSES[:pending]
    end
    
    if inv_users.include? @invitation.user_id
      flash.now[:notice] = t('flash.project.invitations.exists')
      render_new
      return
    end
          
    if @invitation.save
      role = Role.find(@invitation.role_id)
      auction = Auction.find(@project.auction_id)
      
      @role = t("role.name.#{role.send("name")}")
      @auction_link = "<a href=\"/auctions/#{auction.id}\" target=\"_blank\">#{auction.title}</a>"
      @accept_link = "<a href=\"/projects/#{@project.id}/invitations/#{@invitation.id}/accept\">#{t('general.project.invitation.accept')}</a>"
      @reject_link = "<a href=\"/projects/#{@project.id}/invitations/#{@invitation.id}/reject\">#{t('general.project.invitation.reject')}</a>"
      
      body = t('general.project.invitation.body')    
      body.scan(/{[^}]+}/).each do |var|
        body[var] = eval("->"+var+".call").to_s
      end
      @body = body
      
      msg = Message.new(:receiver_id => @invitation.user_id,
                        :topic => t('general.project.invitation.topic'),
                        :body => @body)
      msg.owner_id = @invitation.user_id
      msg.author_id = current_user.id
      
      if msg.save
        flash_t :success
      else
        @invitation.destroy
        flash_t_general :error, 'error.unknown'
      end
      
      redirect_to project_invitations_path    
    else
      render_new
    end
  end
  
  def destroy
    if @invitation.status == Invitation::STATUSES[:pending]
      flash_t :error, 'destroy_error'
      redirect_to project_invitations_path
      return  
    end
    
    if @invitation.destroy
      flash_t :success
    else
      flash_t_general :error, 'error.unknown'
    end
    redirect_to project_invitations_path
  end
  
  def accept 
    @invitation.status = Invitation::STATUSES[:accepted]
    if @invitation.save
      Membership.create(:project_id => @invitation.project_id,
                        :user_id => @invitation.user_id,
                        :role_id => @invitation.role_id)
      flash_t :success
      redirect_to project_info_path(@invitation.project_id)
    else
      flash_t_general 'error.unknown'
      redirect_to panel_messages_path
    end  
  end
  
  def reject   
    @invitation.status = Invitation::STATUSES[:rejected]
    if @invitation.save
      flash_t :success
    else
      flash_t_general 'error.unknown'
    end
    redirect_to panel_messages_path  
  end
  
  def cancel
    unless @invitation.status == Invitation::STATUSES[:pending]
      flash_t :error, 'cancel_error'
      redirect_to project_invitations_path
      return
    end
    
    @invitation.status = Invitation::STATUSES[:canceled]
    
    if @invitation.save
      flash_t :success
    else
      flash_t_general :error, 'error.unknown'
    end
    redirect_to project_invitations_path
  end
  
  private
  
  def get_invitation
    unless Invitation.exists? params[:id]
      flash_t_general :error, 'invitation.dont_exists'
      redirect_to project_invitations_path(@project)
      return
    end
    @invitation = Invitation.find(params[:id])
  end
  
  def get_reciver_invitation
    unless Invitation.exists? params[:id]
      flash_t_general :error, 'invitation.dont_exists'
      redirect_to panel_messages_path
      return
    end
    @invitation = Invitation.find(params[:id])
    
    unless @invitation.user_id == current_user.id
      flash_t_general :error, 'error.privileges'
      redirect_to panel_messages_path
      return
    end
    
    if @invitation.status == Invitation::STATUSES[:canceled]
      flash_t :notice, 'canceled'
      redirect_to panel_messages_path
      return
    end
    
    if @invitation.status == Invitation::STATUSES[:accepted]
      redirect_to project_info_path(@invitation.project_id)
      return
    end
    
    if @invitation.status == Invitation::STATUSES[:rejected]
      redirect_to panel_messages_path
      return
    end  
  end
    
  def check_privileges
    unless can_edit?('member')
  	  flash_t_general :errors, 'error.privileges'
  		redirect_to project_invitations_path
  	end
  end
  
  def render_new
    title_t :new
  	render :action => :new
  end
end

app/controllers/project/members_controller.rb
class Project::MembersController < Project::ApplicationController 
  before_filter :check_privileges, :except => [:index, :destroy]
   
  def index
    title_t :index
    @members = @project.users.paginate :per_page => 15, :page => params[:page]
  end
  
  def update
  	@memb = Membership.where(:user_id => params[:membership][:user_id],
  													:project_id => @project.id).first
    role = params[:membership][:role_id]
  	  	
  	#weryfikacja czlonkostwa
  	if @memb.nil?
  	  flash.now[:error] = t('general.membership.dont_exists')
  	  render_index
  	  return
  	end
  	
  	#weryfikacja uzytkownika
  	if @memb.role_id == Role.get_id('owner') ||
  		 @memb.role_id == Role.get_id('leader')
  	  flash_t :notice, 'cant_change_role'
  	  render_index
  	  return
  	end
  	
  	#weryfikacja roli	 
    if role == Role.get_id('owner') ||
       role == Role.get_id('leader')
      flash_t_general :notice, 'role.invalid_role'
      render_index
      return
    end      
    
    #uaktualnienie roli uzytkownika
  	@memb.role_id = role
  	if @memb.save
  	  flash_t :success
  	  redirect_to project_members_path
		else
		  render_index
  	end
  end
  
  def destroy
		memb = Membership.find(params[:id])
		
		#weryfikacja czlonkostwa
  	if memb.nil?
  	  flash.now[:error] = t('general.membership.dont_exists')
  	  redirect_to project_members_path
  	  return
  	end
  	
  	#weryfikacja roli	 
    if memb.role_id == Role.get_id('owner') ||
       memb.role_id == Role.get_id('leader')
      flash_t :notice, 'cant_delete'
      redirect_to project_members_path
      return
    end 													
	  
	  unless memb.user_id == current_user.id || can_edit?('member')
  	  flash_t_general :errors, 'error.privileges'
  		redirect_to project_members_path
  	end
  	
	  @message = t('general.project.members.message')    
    @message.scan(/{[^}]+}/).each do |var|
      @message[var] = eval("->"+var+".call").to_s
    end
      
    msg = Message.new(:receiver_id => memb.user_id,
                         :topic => t('general.project.members.message_topic'),
                         :body => @message)
	  msg.owner_id = memb.user_id
    msg.author_id = current_user.id
    msg.save

	  #usuwanie uzytkownika
    if memb.destroy
      msg.save
      relese_tickets(memb.user_id)
    	if memb.user_id == current_user.id
    	  flash_t_general :success, 'membership.leave'
    	  redirect_to panel_projects_path
    	else
    	  flash_t :success
    	  redirect_to project_members_path
    	end
  	else
  	  flash_t_general :error, 'error.unknown'
  	  redirect_to project_members_path
    end
  end
  
  private
  
  #sprawdzenie uprawnien do edycji
  def check_privileges
  	unless can_edit?('member')
  	  flash_t_general :errors, 'error.privileges'
  		redirect_to project_members_path
  	end
  end
  
  def render_new
    title_t :new
  	render :action => :new
  end
  
  def render_index
    title_t :index
    render :action => :index
  end
  
  def relese_tickets(user_id)
    tickets = Ticket.where(:user_id => user_id, :project_id => @project.id)
    tickets.each do |t|
      t.status = Ticket::STATUSES[:free]
      t.user_id = nil
      t.save
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def can_edit?(page)
    if @project.active?
      role = Hash.new(false)
      role.merge! @project.user_role(current_user.id).attributes
      role[page]
	  else
	  	false
  	end
  end
  
  def edit_topic?(topic_id)
  	if can_edit?('forum')
  		true
  	elsif current_user.topic_ids.include?(topic_id) && @project.active?
  		true
  	else
  		false
  	end
  end
  
  def edit_post?(post_id)
  	if can_edit?('forum')
  		true
  	elsif current_user.post_ids.include?(post_id) && @project.active?
  		true
  	else
  		false
  	end
  end
end

app/views/project/members/_edit_table.html.erb
<table class="list">
  <thead>
    <tr>
      <th><%= attribute_t 'user.login' %></th>
      <th><%= t('general.contact') %></th>
      <th><%= model_t 'role' %></th>
      <th><%= t('general.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |user| %>
    	<tr>
	    	<% if user.id == @project.owner_id || user.id == @project.leader_id %>
	    		<td><%= link_to user.login, user_path(user) %></td>
	      	<td>
	      		<%= link_to t('general.pm'), :controller => 'panel/messages',
														  :action => :new,
	        										:receiver_login => user.login %> |
	        	<%= mail_to user.email %>
	      	</td>
	      	<td><%= escape_column(@project.user_role(user.id), "name").capitalize %></td>
	      	<td>brak</td>
	    	<% else %>
          <% membership = @project.find_membership(user.id) %>
	    		<%= form_for membership, :url => project_member_path(@project, membership) do |f| %>
	    			<%= f.hidden_field :user_id %>
		    		<td><%= link_to user.login, user_path(user) %></td>
		      	<td>
		      		<%= link_to t('general.pm'), :controller => 'panel/messages',
															  :action => :new,
		        										:receiver_login => user.login %> |
		        	<%= mail_to user.email %>
		      	</td>
		      	<td><%= f.select('role_id',roles_for_select(@project.user_role(user.id)))%></td>
		      	<td>
		      		<%= f.submit t('general.save') %>		      		
		      		<%= link_to t('general.delete'), project_member_path(@project, membership),
		      		                                                     :method =>:delete %>
		      	</td>
		      <% end %>		      
	    	<% end %>	      
	    </tr>
	  <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/project/members/_edit_view.html.erb
<table class="list">
  <thead>
    <tr>
      <th><%= attribute_t 'user.login' %></th>
      <th><%= t('general.contact') %></th>
      <th><%= model_t 'role' %></th>
      <th><%= t('general.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |user| %>
    	<tr>
	    	<% if user.id == @project.owner_id || user.id == @project.leader_id %>
	    		<td><%= link_to user.login, user_path(user) %></td>
	      	<td>
	      		<%= link_to t('general.pm'),
	      		            :controller => 'panel/messages',
												:action => :new,
	        							:receiver_login => user.login %>
	        	 | <%= mail_to user.email %>
	      	</td>
	      	<td><%= escape_column(@project.user_role(user.id), "name").capitalize %></td>
	      	<td><%= t('general.none') %></td>
	    	<% else %>
          <% membership = @project.find_membership(user.id) %>
	    		<%= form_for membership, :url => project_member_path(@project, membership) do |f| %>
	    			<%= f.hidden_field :user_id %>
		    		<td><%= link_to user.login, user_path(user) %></td>
		      	<td>
		      		<%= link_to t('general.pm'),
		      		            :controller => 'panel/messages',
													:action => :new,
		        							:receiver_login => user.login %>
		        	 | <%= mail_to user.email %>
		      	</td>
		      	<td><%= f.select('role_id',roles_for_select(@project.user_role(user.id)))%></td>
		      	<td>
		      		<%= f.submit t('general.save') %>	      		
		      		<%= link_to user.id == current_user.id ? t('general.project.members.leave') : t('general.delete'),
		      		                                                     project_member_path(@project, membership),
		      		                                                     :method =>:delete,
		      		                                                     :confirm => t('general.confirm') %>
		      	</td>
		      <% end %>		      
	    	<% end %>	      
	    </tr>
	  <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/project/members/_normal_table.html.erb
<table class="list">
  <thead>
    <tr>
      <th><%= attribute_t 'user.login' %></th>
      <th><%= t('general.contact') %></th>
      <th><%= model_t 'role' %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |user| %>
      <tr>
        <td><%= link_to user.login, user_path(user) %></td>
        <td>
        	<%= link_to t('general.pm'), :controller => 'panel/messages', :action => :new, :receiver_login => user.login %> | 
        	<%= mail_to user.email %>
        </td>
      	<td>
      		<%= escape_column(@project.user_role(user.id), "name").capitalize %>        	
      	</td>
    	</tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/project/members/_standard_view.html.erb
<table class="list">
  <thead>
    <tr>
      <th><%= attribute_t 'user.login' %></th>
      <th><%= t('general.contact') %></th>
      <th><%= model_t 'role' %></th>
      <th><%= t('general.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |user| %>
      <tr>
        <td><%= link_to user.login, user_path(user) %></td>
        <td>
        	<%= link_to t('general.pm'),
        	            :controller => 'panel/messages',
        	            :action => :new,
        	            :receiver_login => user.login %> 
        	 | <%= mail_to user.email %>
        </td>
      	<td>
      		<%= escape_column(@project.user_role(user.id), "name").capitalize %>        	
      	</td>
      	<td>
      	  <% memb = @project.find_membership(user.id) -%>
      	  <% if memb.user_id == current_user.id && @project.owner_id != current_user.id -%>
      	    <%= link_to t('general.project.members.leave'), project_member_path(@project, memb),
		      		                                              :method =>:delete,
		      		                                              :confirm => t('general.confirm') %>
      	  <% else -%>
      	    <%= t('general.none') %>
      	  <% end -%>
      	</td>
    	</tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/project/members/index.html.erb
<%= render 'project/shared/menu' %>

<div class="span-14 prepend-1">
	<% if can_edit?('member') %>
		<%= render 'edit_view' %>
	<% else %>
		<%= render 'standard_view' %>
	<% end %>
</div>

app/views/project/members/show.html.erb
<%= render 'project/shared/menu' %>

<div class="span-10 prepend-1">
	<% if can_edit?('user') %>
		<%= render 'edit_table' %>
	<% else %>
		<%= render 'normal_table' %>
	<% end %>
</div>